//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionScolaire
{
    using System;
    using System.Collections.Generic;
    
    public partial class Avertissement
    {
        public int id_A { get; set; }
        public Nullable<int> id_E { get; set; }
        public string Motif_A { get; set; }
        public Nullable<int> Severite_A { get; set; }
    
        public virtual Etudiant Etudiant { get; set; }
    }
}
