//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionScolaire
{
    using System;
    using System.Collections.Generic;
    
    public partial class Classe
    {
        public int id_C { get; set; }
        public Nullable<int> Etage_C { get; set; }
        public string Superficie_C { get; set; }
        public string SalleInformatique_C { get; set; }
        public string Labo_C { get; set; }
        public string TravauxPratique_C { get; set; }
        public string Bibliotheque_C { get; set; }
    }
}
