//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionScolaire
{
    using System;
    using System.Collections.Generic;
    
    public partial class detail
    {
        public int idCom { get; set; }
        public Nullable<int> idProduit { get; set; }
        public Nullable<int> qte { get; set; }
    
        public virtual produit produit { get; set; }
    }
}
