//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionScolaire
{
    using System;
    using System.Collections.Generic;
    
    public partial class Etudiant
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Etudiant()
        {
            this.Avertissements = new HashSet<Avertissement>();
            this.Notes = new HashSet<Note>();
        }
    
        public int id_E { get; set; }
        public string Nom_E { get; set; }
        public string Prenom_E { get; set; }
        public Nullable<System.DateTime> Datenaissance_E { get; set; }
        public Nullable<int> NiveauScolaire_E { get; set; }
        public string Adresse_E { get; set; }
        public string Sexe_E { get; set; }
        public string Tel_E { get; set; }
        public string NomPere_E { get; set; }
        public string MetierPere_E { get; set; }
        public string TelPere_E { get; set; }
        public string NomMere_E { get; set; }
        public string MetierMere_E { get; set; }
        public string TelMere_E { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Avertissement> Avertissements { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Note> Notes { get; set; }
    }
}
