//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionScolaire
{
    using System;
    using System.Collections.Generic;
    
    public partial class Etudiant
    {
        public int id_E { get; set; }
        public string Nom_E { get; set; }
        public string Prenom_E { get; set; }
        public Nullable<System.DateTime> Datenaissance_E { get; set; }
        public Nullable<int> NiveauScolaire_E { get; set; }
        public string Adresse_E { get; set; }
        public string Sexe_E { get; set; }
        public string Tel_E { get; set; }
        public string NomPere_E { get; set; }
        public string MetierPere_E { get; set; }
        public string TelPere_E { get; set; }
        public string NomMere_E { get; set; }
        public string MetierMere_E { get; set; }
        public string TelMere_E { get; set; }
    }
}
