//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionScolaire
{
    using System;
    using System.Collections.Generic;
    
    public partial class Matiere
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Matiere()
        {
            this.Notes = new HashSet<Note>();
        }
    
        public int id_M { get; set; }
        public string Nom_M { get; set; }
        public Nullable<int> id_P { get; set; }
        public Nullable<int> NumSalle_M { get; set; }
    
        public virtual Professeur Professeur { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Note> Notes { get; set; }
    }
}
