//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionScolaire
{
    using System;
    using System.Collections.Generic;
    
    public partial class Note
    {
        public int id_N { get; set; }
        public Nullable<int> id_M { get; set; }
        public Nullable<int> id_E { get; set; }
        public Nullable<int> NumControle_N { get; set; }
        public Nullable<int> Moyenne_N { get; set; }
    
        public virtual Etudiant Etudiant { get; set; }
        public virtual Matiere Matiere { get; set; }
    }
}
